<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-L24ILI7K" failures="0" tests="1" name="Trial1.ExceptionTimeOut" time="0.021" errors="1" timestamp="14 May 2019 04:14:41 GMT" skipped="0">
  <testcase classname="Trial1.ExceptionTimeOut" name="infiniteloopTest" time="0.021">
    <error message="
Expected exception of type class java.lang.NumberFormatException but got org.testng.internal.thread.ThreadTimeoutException: Method Trial1.ExceptionTimeOut.infiniteloopTest() didn&#039;t finish within the time-out 2" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Expected exception of type class java.lang.NumberFormatException but got org.testng.internal.thread.ThreadTimeoutException: Method Trial1.ExceptionTimeOut.infiniteloopTest() didn't finish within the time-out 2
at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:68)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1130)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:615)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.testng.internal.thread.ThreadTimeoutException: Method Trial1.ExceptionTimeOut.infiniteloopTest() didn't finish within the time-out 2
at java.base@12.0.1/java.nio.Buffer.clear(Buffer.java:425)
at java.base@12.0.1/java.nio.ByteBuffer.clear(ByteBuffer.java:1138)
at java.base@12.0.1/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:236)
at java.base@12.0.1/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
at java.base@12.0.1/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:104)
at java.base@12.0.1/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:184)
at java.base@12.0.1/java.io.PrintStream.write(PrintStream.java:606)
at java.base@12.0.1/java.io.PrintStream.print(PrintStream.java:676)
at java.base@12.0.1/java.io.PrintStream.println(PrintStream.java:812)
at app//Trial1.ExceptionTimeOut.infiniteloopTest(ExceptionTimeOut.java:12)
at java.base@12.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@12.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base@12.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@12.0.1/java.lang.reflect.Method.invoke(Method.java:567)
at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:40)
at java.base@12.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base@12.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@12.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@12.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@12.0.1/java.lang.Thread.run(Thread.java:835)
]]>
    </error>
  </testcase> <!-- infiniteloopTest -->
</testsuite> <!-- Trial1.ExceptionTimeOut -->
